name: FTRCore
version: 1.0.0
main: me.skyfallin.plugin.Main
description: A plugin for managing all custom items on the server.
author: Skyfallin_
commands:
  artifactinfo:
    usage: /<command>
    description: Returns info on the artifact slot.
  runeinfo:
    usage: /<command>
    description: returns info...
  getrune:
    usage: Error?
    description: Obtain a rune of the given skill type.