name: RunicCore
version: 2.0.0
api-version: 1.13
main: com.runicrealms.plugin.RunicCore
description: Core plugin for the "Runic Realms" server
author: Skyfallin_
loadbefore: [Quests]
depend: [RunicCharacters]
softdepend: [PlaceholderAPI]
commands:
  artifactinfo:
    usage: /<commands>
    description: Returns info on the artifact slot.
  currency:
    usage: /<commands>
    description: Give a player currency!
  experience:
    usage: /<commands>
    description: Check your experience
  exp:
    usage: /<commands>
    description: Check your experience
  spell:
    usage: /<commands>
    description: Base for all oldspells commands
  party:
    usage: /<commands>
    description: Base for all party commands
  set:
    usage: /<commands>
    description: set a player's info
  mana:
    usage: /<commands>
    description: sets your mana to full
  gathertool:
    usage: /<commands>
    description: give yourself a gathering tool
  runicgive:
    usage: /<commands>
    description: give yourself something
  npcbuilder:
    usage: /<commands>
    description: make an npc!
  spellpoint:
    usage: /<commands>
    description: add a spellpoint to a player
  travel:
    usage: /<commands>
    description: travel to location
  tutorial:
    usage: /<commands>
    description: used for tutorial-related commands