name: FTRCore
version: 2.0.0
main: us.fortherealm.plugin.Main
description: Core plugin for the "For the Realm" server
author: Skyfallin_
commands:
  artifactinfo:
    usage: /<command>
    description: Returns info on the artifact slot.
  skill:
    usage: /<command>
    description: Base for all oldskills commands
  party:
    usage: /<command>
    description: Base for all party commands