name: FTRCore
version: 2.0.0
main: us.fortherealm.plugin.Main
description: Core plugin for the "For the Realm" server
author: Skyfallin_
commands:
  artifactinfo:
    usage: /<command>
    description: Returns info on the artifact slot.
  runeinfo:
    usage: /<command>
    description: returns info...
  getrune:
    usage: Error?
    description: Obtain a rune of the given skill type.