name: RunicCore
version: 2.0.0
api-version: 1.15
main: com.runicrealms.plugin.RunicCore
description: Core plugin for the "Runic Realms" server
author: Skyfallin, Excel, Destiny
loadbefore: [Quests]
softdepend: [PlaceholderAPI]
depend: [MythicMobs, NBTAPI, RunicChat]
commands:
  artifactinfo:
    usage: /<commands>
    description: Returns info on the artifact slot.
  currency:
    usage: /<commands>
    description: Give a player currency!
  experience:
    usage: /<commands>
    description: Check your experience
  exp:
    usage: /<commands>
    description: Check your experience
  spell:
    usage: /<commands>
    description: Base for all oldspells commands
  gmc:
    usage: /<commands>
    description: Creative
  gms:
    usage: /<commands>
    description: Survival
  gmsp:
    usage: /<commands>
    description: Spectator
  group:
    usage: /<commands>
    description: Base for all party commands
  party:
    usage: /<commands>
    description: Base for all party commands
  set:
    usage: /<commands>
    description: set a player's info
  mana:
    usage: /<commands>
    description: sets your mana to full
  resettree:
    usage: /<commands>
    description: reset skill tree
  runicgive:
    usage: /<commands>
    description: give yourself something
  npcbuilder:
    usage: /<commands>
    description: make an npc!
  spellpoint:
    usage: /<commands>
    description: add a spellpoint to a player
  travel:
    usage: /<commands>
    description: travel to location
  tutorial:
    usage: /<commands>
    description: used for tutorial-related commands
  boost:
    usage: /<commands>
    description: store stuff
  map:
    usage: /<commands>
    description: View the online runic realms map
  runicdamage:
    usage: /<commands>
    description: Fixes damage logic in MM skills
  runicfirework:
    usage: /<commands>
    description: Spawns a firework
  outlaw:
    usage: /<commands>
    description: Toggle player outlaw mode
  spawn:
    usage: /<commands>
    description: Select hearthstone
  runicvote:
    usage: /<commands>
    description: Gain a voting exp bonus