name: RunicCore
version: 2.1.0
api-version: 1.15
main: com.runicrealms.plugin.RunicCore
description: Core plugin for the "Runic Realms" server
author: Skyfallin, Excel, Destiny
loadbefore: [ Quests ]
softdepend: [ PlaceholderAPI ]
depend:
  - MythicMobs
  - WorldGuard
  - NBTAPI
  - NametagEdit
  - RunicChat
  - RunicCommon
  - RunicDatabase
  - RunicRestart
  - RunicNpcs
  - RunicItems
  - HolographicDisplays
  - ProtocolLib
  - ViaVersion
  - LuckPerms
  - ModelEngine
  - GlowAPI
commands:
  3d:
    usage: /<commands>
    description: Get a 3d version of your weapon!
  currency:
    usage: /<commands>
    description: Give a player currency!
  party:
    usage: /<commands>
    description: Base for all party commands
  boost:
    usage: /<commands>
    description: store stuff
  map:
    usage: /<commands>
    description: View the online runic realms map
  runicdamage:
    usage: /<commands>
    description: Fixes damage logic in MM skills
  runicfirework:
    usage: /<commands>
    description: Spawns a firework
  spawn:
    usage: /<commands>
    description: Select hearthstone
  runicvote:
    usage: /<commands>
    description: Gain a voting exp bonus