name: RunicCore
version: 2.0.0
api-version: 1.13
main: com.runicrealms.plugin.RunicCore
description: Core plugin for the "For the Realm" server
author: Skyfallin_
loadbefore: [Quests]
commands:
  artifactinfo:
    usage: /<commands>
    description: Returns info on the artifact slot.
  currency:
    usage: /<commands>
    description: Give a player currency!
  skill:
    usage: /<commands>
    description: Base for all oldskills commands
  party:
    usage: /<commands>
    description: Base for all party commands
  set:
    usage: /<commands>
    description: set a player's info
  mana:
    usage: /<commands>
    description: sets your mana to full
  gathertool:
    usage: /<commands>
    description: give yourself a gathering tool
  npcbuilder:
    usage: /<commands>
    description: make an npc!
  skillpoint:
    usage:
    description: add a skillpoint to a player
  tutorial:
    usage: /<commands>
    description: used for tutorial-related commands