package com.runicrealms.plugin.item.util;

import com.runicrealms.runicitems.RunicItemsAPI;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

public class ItemRemover {

    /**
     * Removes items from a player's inventory, typically when they purchase an item in a shop. Handles custom
     * NBT through ItemStacks generated by RunicItems
     *
     * @param player to remove items from
     * @param itemStack item to remove
     * @param amount amount of item to remove
     */
    public static void takeItem(Player player, ItemStack itemStack, int amount) {
        int to_take = amount;
        for (ItemStack player_item : player.getInventory().getContents()) {
            if (player_item != null) {
                if (RunicItemsAPI.isRunicItemSimilar(itemStack, player_item)) {
                    int take_next = Math.min(to_take, player_item.getAmount());
                    remove(player, player_item, take_next);
                    to_take -= take_next;
                    if (to_take <= 0) { //Reached amount. Can stop!
                        break;
                    }
                }
            }
        }
    }

    private static void remove(Player p, ItemStack toR, int amount) {
        ItemStack i = toR.clone();
        i.setAmount(amount);
        p.getInventory().removeItem(i);
    }
}
